twig:
  #form_themes:
   # - LexikFormFilterBundle:Form:form_div_layout.html.twig

lexik_form_filter:
  listeners:
    doctrine_orm: true
    doctrine_dbal: true
    doctrine_mongodb: false

  force_case_insensitivity: false
  encoding: ~ # Encoding for case insensitive LIKE comparisons. For example: UTF-8

  where_method: ~  # null | and | or

  condition_pattern: text.starts  # text.contains, text.starts, text.ends, text.equal.