services:
  pagerfanta.view.default:
    class: Pagerfanta\View\DefaultView
    public: false
    tags: [{ name: pagerfanta.view, alias: default }]

white_october_pagerfanta:
  exceptions_strategy:
    out_of_range_page:        ~
    not_valid_current_page:   ~