sonata_user:
  class:
    user: App\Entity\SecurityUser
    group: App\Entity\SecurityGroup
  table:
    user_group: security_user_user_group

  admin: # Admin Classes
    user:
      class:          App\Admin\UserAdmin
      controller:     SonataAdminBundle:CRUD
      translation:    SonataUserBundle
    group:
      class:          App\Admin\GroupAdmin
      controller:     SonataAdminBundle:CRUD
      translation:    SonataUserBundle

parameters:
  sonata.user.admin.user.entity: 'App\Entity\SecurityUser'
  sonata.user.admin.group.entity: 'App\Entity\SecurityGroup'
  #sonata.user.admin.user.class: 'App\Admin\SecurityUserAdmin'
  #sonata.user.admin.group.class: 'App\Admin\SecurityGroupAdmin'