vich_uploader:
    db_driver: orm

    mappings:

        security_user_image:
            uri_prefix: /uploads/images/security_user
            upload_destination: '%kernel.project_dir%/public/uploads/images/security_user'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

