# related to app/config/security.yml

security:
    role_hierarchy:
        ROLE_APP_USER:
            - ROLE_USER
            - ROLE_DASHBOARD_USER            

        ROLE_APP_ADMIN:
            - ROLE_USER
            - ROLE_ADMIN

