<?php

namespace App\Admin;


use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Route\RouteCollection;

abstract class _BaseAdmin_ extends AbstractAdmin
{
    public $actions = [
        'edit' => array(),
        'show' => array(),
    ];

    public function getClass()
    {
        return parent::getClass(); // TODO: Change the autogenerated stub
    }

    protected function configureRoutes(RouteCollection $collection)
    {
        // to remove a single route
        $collection->remove('delete');
        // OR remove all route except named ones
        return $collection->clearExcept(array('create','list','edit', 'show'));
    }
}