<?php

namespace App\Admin;


use Sonata\AdminBundle\Admin\AbstractAdmin;

abstract class _BaseAdmin_ extends AbstractAdmin
{
    public $actions = [
        'edit' => array(),
        'show' => array(),
    ];

    public function getClass()
    {
        return parent::getClass(); // TODO: Change the autogenerated stub
    }
}